### ISSUE TITLE
Infix operator precedence depends on spacing

### ISSUE THREAD

**Issue by simonkeys** [halirutan/Mathematica-IntelliJ-Plugin#103]
With an expression like

`a \[CircleDot] b@c`

If you select `b` and choose Extend Selection, the `b@c` is selected, which I think is the correct behavior. However, if there is no space between the `\[CircleDot]` and `b`:

`a \[CircleDot]b@c`

then selecting `b` and extending the section results in `\[CircleDot]b` being selected, which I think is incorrect.

**Comment by halirutan** [comment]
Thanks for reporting this, I'm aware of this flaw but this was more or less a conscious choice to not support this. It would have added a big chunk of complexity to the lexer and parser with very little profit. 

Things like `\[CirclePlus]` is a named character like `\[Alpha]`. Some of them are operators and some can be part of a symbol. Since the normal operators like `+`, `&&`, etc. are not allowed in symbol-names, I can match them easily which makes a the lexing and parsing of a file fast.

If I included this separation of named characters into symbols and operators, the rules for matching them would become much more complex as I would need to maintain a list that is checked, instead of a simple pattern. Currently, I'm doing none of this as you can see [in this line](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/develop/src/de/halirutan/mathematica/lang/lexer/Mathematica.flex#L48). I have a simple generic pattern for named characters.

If I included this correctly, not only `\[CircleDot]` needs to be fixed. In essence, I need to add an additional match to most operators. Mathematica is in this regard very unfriendly to a language plugin developer as e.g. all three of these means the same

```mma
a&&b
a\[And]b
And[a,b]
```

The problem, however, is not that this cannot be done. The problem is that unlike Mathematica, that parses and evaluates code only every once in a while, the plugin needs to lex, parse and analyze your file on each keystroke and at the very bottom of this chain is the lexer and the parser.

So for the time being, you are stuck with using

```mma
CircleDot[a, b@c]
```

# Edit

To answer your question: For the plugin `a \[CircleDot] b@c` means `a*\[CircleDot]*b@c` and in `a \[CircleDot]b@c` the `\[CircleDot]b` is regarded as one symbol. However, in Mathematica, this will still be correctly interpreted.

**Comment by simonkeys** [comment]
Thanks for the detailed explanation. Now that I'm aware of it, it's easy enough to work around.
