### ISSUE TITLE
Certain text elements are incorrectly colored

### ISSUE THREAD

**Issue by MrHirenP** [halirutan/Mathematica-IntelliJ-Plugin#104]
Patterns inside `Rules` are incorrectly colored as 'Module Variables'.  It should be colored as 'Patterns and Arguments'.

Local variables of built in functions are incorrectly colored as 'Module Variables'.  It should be colored as 'Block Variables'.

*Mathematica* Plugin

![screen shot 2018-06-26 at 11 15 06 am](https://user-images.githubusercontent.com/26680488/41922041-39d12008-7932-11e8-8407-15443e856a2f.png)

*Mathematica* Front End

![screen shot 2018-06-26 at 11 14 59 am](https://user-images.githubusercontent.com/26680488/41922051-4075d994-7932-11e8-9647-7b00905a8698.png)

**Comment by halirutan** [comment]
I need to check how this is currently handled by the dev-version.

**Comment by halirutan** [comment]
@MrHirenP In the beta version (you can [read here how to use it](http://halirutan.de/programming/MathematicaPlugin3/)), the *recognition* of the variables in your examples is fixed. However, I want to make clear that my goal is not to reproduce the coloring of the front end. The reason is simple: It doesn't make sense at all and it seems to exist purely for historical reasons.

We have basically only a few very important "scoping types" in Mathematica. The most important one is `RuleDelayed` because in essence, `f[x_] :> x` is similar to the downvalue of `f[x_] := x`. Then, we have 3 scoping functions `Module`, `With`,  and `Block` (there are some more like ``Internal`InheritedBlock`` but let's ignore this for now). All three of them are different, because they try to implement different scoping types: lexical scoping, value replacement, and dynamic scoping. Why `Block` is the only one that gets a different color is beyond my understanding.

However, what is even more absurd is that `Integrate` gets the same coloring as `Block` because it is simply wrong. The question is, what should the coloring indicate? Answer: It should suggest to the user that the `x` in `Integrate` belongs to this function and is scoped like `Block`, right? Obviously, this is not the case. In fact, `Integrate` does no scoping at all

![img](http://i.stack.imgur.com/osngA.png)

So the inner `x` is evaluated to ``Global`x`` although the highlighting suggests something completely different. Other functions, like `RegionPlot` however *do* scope their variables and for some of all these functions it's pointed out in the documentation that they *effectively use `Block` to scope their variables*.

For the Plugin on the other hand, it is important how a variable is scoped because when you rename a variable, it only renames the usages that belong to the same variable. So if you rename an `x` inside `Module`, a global `x` or an `x` in another `Module` is not renamed.

In the beta-version of the plugin, I had to rewrite the complete framework  of how local variables are found and colored. I made it more *Mathematica-like* since we now have so many functions (most of them plotting commands) that do scoping. Now, each function gets an attribute that says something similar to "behaves like `Table` and can have scoped variables on places 3-4". That means that `Module`, `With`, and `Block` fall under the same categroy and are currently highlighted in simple green.

I might change this in future, but currently getting a stable and usable Plugin for IDEA 2018 is a more pressing matter. I have played with the idea of

1. Making patterns in definitions and rules *green and  italic*
2. Making `Module`, `With`, and `Block` variables a noticably different green-bluish so that you can instantly tell in a long function definition what are local variables and what are argument patterns. Or another idea: I leave them at *green and not-italic* and..
3. ... make all other local variables in `Table`, `Compile`, etc.. a slightly different color.

At least to me, it is important to differentiate between argument-patterns, local variables, and variables localized by `Table` and friends.

I need to discuss this with @szhorvat and if you like, you can always join the [gitter chat](https://gitter.im/IntelliJ-Plugin-Developers/Lobby) and chime into the conversation.
