### ISSUE TITLE
Support refactoring for new-style packages

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#110]
[New-style packages](https://mathematica.stackexchange.com/a/176489/12) make a symbol public as 

    PackageExport["MySym"]

or package-scope as

    PackageScope["myPrivateSym"]

Notice the quoted symbol names.

Refactoring should detect these, and handle them appropriately. Is this possible?

I assume it should not be too hard because the good new is that:

This only needs to be done when one of a few symbols (like `PackageExport`) appears at file scope and contains a single string argument. According to the discussion I linked above, these symbols do not evaluate. Instead, they are used by a static analyser to detect which symbol goes into which context, before the package is actually loaded. They are more akin to C's preprocessor directives. E.g. `PackageExport /@ list` is not valid.

**Comment by halirutan** [comment]
Several steps are required for this

- [x] Make them autocomplete
- [x] Include these macros known to the resolver so that they don't appear as warnings
- [x] Make the string arguments resolve to the actual symbols and add refactoring
- [x] Create *Intention* that let's you easily create `PackageExport`, ... for defined symbols (**works with autocompletion inside the string**)
- [x] Create *Inspection* that checks if these macros are on a separate line with nothing more on it and if the strings resolve
