### ISSUE TITLE
Too sensitive inspection 'function scope'

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#115]
```#  -> # + 1 & /@ data```

![image](https://user-images.githubusercontent.com/15227576/53445786-ad6d7e80-3a11-11e9-92b1-180f183153f3.png)

What can we do about that perfectly valid piece of code? Is it viable to restrict that inspection only to 'options pattern' part of functions calls?
Or am I left with disabling that inspection or getting a habit of using more parentheses?

**Comment by szhorvat** [comment]
Useful linting will always have false positives, and it's up to you to decide which warning should be ignored and which should be acted upon.

In general, IDEA has a feature where it can suppress an individual instance of an inspection.

https://www.jetbrains.com/help/idea/suppressing-inspections.html

This is done through the addition of special comments.

I believe the WL plugin does not yet support this. @halirutan will correct me if I'm wrong. I know we discussed this in the chatroom before, but with the addition of linting features it became more important.

**Comment by szhorvat** [comment]
Linking https://github.com/halirutan/Mathematica-IntelliJ-Plugin/issues/93

**Comment by kubaPod** [comment]
@szhorvat Currently I just disabled it as it is not a frequent problem for me. 

I don't think disabling specific cases is an option here, it rather feels like we have two patterns which are affected: functions in options and rules in functional code. The former needs that inspection and the latter, in most cases, does not. (that is probably a simplification)

So the question to @halirutan is, is it viable to address only one? If not - fine, a comment about it could be added to the description and for me it solves the issue.

**Comment by halirutan** [comment]
I have seen this as well and the solution is to add some further code, that checks if the LHS of the rule contains a `#` (or friends). *Then*, I can assume the user knows what he was doing. 

In general, this a good case where I can show @kubaPod why [his suggestions on SE](https://mathematica.meta.stackexchange.com/a/2436/187) are excellent but very hard to implement without annoying *some* users.

In the case you reported here, it is extremely easy to get rid of the warning. Just make the scope explicit by putting `()` around it

```mma
(# -> # + 1) & /@ data
```
However, when I make an inspection that counts, e.g. the number of arguments for functions and reports wrong cases, it is not possible to *change* the AST so that the inspection doesn't fire. So when a pro user really wants to write

```mma
With[{args=Sequence[x,{x,0,1}]},
    Plot[args]
]
```

and I show him that this is wrong because `Plot` takes at least two arguments, he has no way of changing the code. I cannot even check if the arguments contain a `Sequence`, which would suggest that the user knows what he is doing. I would have to resolve `args`, see that it is inside a `With` and inspect the definition to find that. This is pretty nasty (and is bound to break in many cases).

One solution is to implement what Szabolcs mentioned: A comment that lets you turn off inspections for just one expression or the file. I hate these annotations and I'm sure and find them ugly. And it would probably take several iterations until I get this right.

Conclusion: I'll fix situations like yours when the rule contains a `#` on the LHS and give the ugly comment annotations another thought.

**Comment by kubaPod** [comment]
@halirutan @szhorvat I tried hard to make clear here and in linked SE topic that I understand problems, don't need perfect solutions, know alternatives and the main point was to have a clean list of features to refer in future.
I hope you make those comments for future visitors sake, otherwise it means you think I'm retarded :)

**Comment by szhorvat** [comment]
> In the case you reported here, it is extremely easy to get rid of the warning. Just make the scope explicit by putting `()` around it

How difficult would it be to implement and auto-fixer for this (or whatever that's called in by IntelliJ)?

The lightbulb comes up, click it, "Parenthesize function"

----

I think Kuba's suggestion was to try to detect whether something is meant to be an option from context. This is absolutely not possible in a _general_ way, but would it be possible to just not fire the inspection within the first level `Map` and `Apply`? That would take care of the vast majority of these.  Other cases, such as similar package functions (like `IGVertexMap`) are much less common.

Is it technically feasible to go up _one_ level and check if that's `Map` or `Apply`?

**Comment by halirutan** [comment]
@szhorvat I think with checking if there is a `#` in the LHS of the rule, we pretty much catch most cases.
I implemented this extension and a basic quick-fix

![scope](https://user-images.githubusercontent.com/511683/53492534-61661c80-3a99-11e9-8157-34c7c2312935.gif)

Let's see how this works in practice.
