### ISSUE TITLE
Collapsing only cell-group-like sections.

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#120]
It woulld be nice to be able to 'Collapse all cell groups'  which would collapse all `(* ::Section:: *)` and friends but not functions/code blocks.

**Comment by szhorvat** [comment]
I have wished for the very same thing in the past. It's one of the reasons why I recently switched to editing [the IGraph/M test file](https://github.com/szhorvat/IGraphM/tree/master/Tests) with the FE instead of IDEA.  (I should note that that file has many issues, and could be made more convenient to edit with the IDE.)
