### ISSUE TITLE
Templates for Sections / cell group headers

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#128]
It seems that this can potentially be useful for wider audience:

![image](https://user-images.githubusercontent.com/15227576/58935864-a374bd80-876e-11e9-9543-84d5a6428fd9.png)

I am not sure what is the best abbreviation but `"gr"|"cg" + MenuCommandKey` sounds reasonable.

So I am asking for a build in set of `gr{N}` templates which should insert

```
(* ::$STYLE.N$::*)
(*$SELECTION$*)
```

and where 

```
style : {
 1: Title,
 2: Chapter,
 3: Subchapter
 4: Section
 5: Subsection
 6: Subsubsection
 7: Subsubsubsection
 8: Subsubsubsubsection
}
```

While I don't use first three at all it is probably good to keep it consistent with Package/Default styles.

Speaking of being consistent, in MMA 7 refers to Text and 8 to Code. Code is default and is anyone using Text cells in packages anyway? That is why I'd make an exception to support those deeper sections which don't have MenuCommandKey associated with.

**Comment by halirutan** [comment]
Please try pressing `Ctrl`+`/` to open a new comment `(**)` with the cursor inside. Then press `Ctrl`+`Space` to trigger completion. 

![img](http://i.imgur.com/hHQ3ddJ.png)

If the completion pop-up is open, you can start typing e.g. `Sub..` to quickly navigate to the item you want.

**Comment by kubaPod** [comment]
Thanks, I wasn't aware of it. The problem is to create "mysection" section one need to 

> Ctrl+/ --> Ctrl+Space --> naviage+Enter --> move to the next line --> Ctrl+/ --> type "mysection"

With live templates:

> type "gr4"+Tab --> type "mysection" 

So I'd rather create custom gr* templates. Otoh maybe your comment templates could insert 

`(*` + ` ::Section:: *)\n(*$SELECTION$` + `*)`?

Not sure if that wouldn't be confusing.

**Comment by halirutan** [comment]
> create "mysection" section one need to

If you are inside a comment and press `Ctrl`+`Shift`+`Enter`, then you end up in the next line. For something that you tend to use only a couple of times inside a package file, I feel there is no need to over-optimize this

![comment](https://user-images.githubusercontent.com/511683/59106715-5ee84e00-8937-11e9-96d7-6694dae29592.gif)

> maybe your comment templates could insert

I would need to rework this completely because the completion list also contain things like `:Author:` which don't need a separate comment for the value. I effectively needed to implement different insert handlers where I now don't need any of this.

We shouldn't forget that this is *not* a widely used feature. It's used by us, who like to ensure that packages look also decent when opened in the front end. I did not find any usage of these sectioning comments in the AddOns of Mathematica itself. They tend to use

![img](http://i.imgur.com/dc8GXKA.png)

Including these things as default LiveTemplates, however, would mean that they will *always* pop-up as a suggestion when the prefix of what you typed matches. If you like to use this on your machine, it might be faster to create one of your `gr`-templates and edit the XML file where this is stored directly.

For me, the config files are located under

```
$HOME/.IntelliJIdea2019.1/config/templates
```

**Comment by kubaPod** [comment]
> We shouldn't forget that this is not a widely used feature.

That note is really on point, somehow I assumed it is a feature everyone needs, but you are of course right :)
