### ISSUE TITLE
Add support for custom syntax coloring on symbol level

### ISSUE THREAD

**Issue by mxknt** [halirutan/Mathematica-IntelliJ-Plugin#129]
@halirutan First off, I'd like to say thanks for your work on this great plugin!

I'm working on a project with a large body of domain specific symbols, so the syntax coloring built into the plugin doesn't help much - since the majority of symbols I'm using aren't built in - most of the code I'm working with is all the same color. I was wondering about adding support to set the color of individual symbols to make things more readable for me.

I don't really use Java, but I've been able to build the plugin from source - so if you could point me in the right direction I'd be happy to try and do it myself.

Thanks!
mk

**Comment by halirutan** [comment]
That will be hard because the current code-base is not open-source anymore. This step was necessary as I wanted to bring the Wolfram Language Plugin to the new [JetBrains Marketplace](https://plugins.jetbrains.com/marketplace).

However, the new 2019.1 version is available for IDEA 2019.1.3 and I will soon publish a release that targets all 2019.1 versions. At this moment, the WL Plugin is still free for everyone using the Community edition of IDEA. For Ultimate IDEA you need a subscription but I give them away cheaply for a private license:

- [Wolfram Language Plugin](https://plugins.jetbrains.com/plugin/7232-wolfram-language/pricing#edition=personal)

That all being said, if you provide a short complete snippet of what your DSL looks like, I can give you some pointers on how you can work with such code even if the symbols are not differently colored.

**Comment by halirutan** [comment]
Closing for missing feedback
