### ISSUE TITLE
License question.

### ISSUE THREAD

**Issue by ayaka209** [halirutan/Mathematica-IntelliJ-Plugin#137]
I read your License page https://wlplugin.halirutan.de/docs/licensing/

>but the plan is to support a license scheme that is similar to IntelliJ IDEA.

> Personal license for non-commercial use
> People working on private, non-commercial projects or people who want to actively support the development of the Wolfram Language Plugin can get a license for a small subscription fee which can be paid monthly or yearly.
> 
> The plan is to offer this license for approx 3 Euro/month if paid monthly or 30 Euro/year if paid yearly. The price is similar to or smaller than what you would pay for one beer in a bar in Germany.
> 
> Commercial licenses
> People using the Wolfram Language Plugin for their work can get a commercial license subscription paid monthly or yearly. The plan is to offer this license for approx 12 Euro/month if paid monthly or 120 Euro/year if paid yearly.

But, for Intellij IDEA, Personal License can be used for personal commercial project.
EULA shown in marketplace page also didn't mention the commercial use.

Please clarify whether the license for individual purchased from the marketpace can be used for commercial projects.

Thank you.

**Comment by halirutan** [comment]
I know that I should clear this section up, but the JB Marketplace is still not ready for Community products, and most of my users don't have Ultimate anyway and can work with the WL plugin for free at the moment. Additionally, I'm neither a native English speaker nor a lawyer, and I have a particular distaste for the latter ones. It will be difficult for me to write the licensing part so that it is waterproof and, honestly, I don't intend to do this. There is no way to enforce the rules anyway.

The commercial license was *meant* for people who use the plugin to earn money with it. Here in Germany, everyone who makes money as a freelancer needs to have business and I realize that this might not be the case everywhere in the world.

My view on all this is simple: If you are an "individual" and you make a ton of money as a freelancer, I would highly appreciate if you buy a commercial license (or 10 if you like). However, if the commercial license is something you cannot afford, then use your "personal license". I'm well aware that 12 Euro means something entirely different in some places in the world.

I will try to update this document on the webpage in the near future.

**Comment by ayaka209** [comment]
Thank you for the clarification.

**Comment by halirutan** [comment]
@ayaka209 I tried to be more concise on the [licensing page](https://wlplugin.halirutan.de/docs/licensing/). Most importantly, for now, I removed the restriction that private licenses need to be used for non-commercial projects only. I'll check with JB if they have a clear definition of personal and commercial plugin licenses.

**Comment by ayaka209** [comment]
@halirutan thanks, I have purchased one.
