### ISSUE TITLE
Incorrect "Unused local variable" inspection for user-defined global variables

### ISSUE THREAD

**Issue by gerli** [halirutan/Mathematica-IntelliJ-Plugin#141]
In the following, `$MachinePrecision` is not flagged in the `Block` as unused (correct) but `$MyGlobalVariable` is flagged as unused (incorrect):

```
$MyGlobalVariable = 5;
f[] := {$MachinePrecision, $MyGlobalVariable};

Block[{$MachinePrecision = 15, $MyGlobalVariable = 10},
    f[]
]
```

**Comment by halirutan** [comment]
Yes, you are right. As you see for built-in symbols it doesn't show the warning, because it custom to set something like `$RecursionLimit` within a `Block`. I see your point, but the vast majority of people also use `Block` as a light-weight alternative to `Module` and they want to see warnings when they don't use a variable.

I'm not sure how to handle this. I mean, I can turn off the check for `Block` completely, but that would probably annoy people who use the inspection for this purpose.

@szhorvat Can you add something to the discussion?

**Comment by gerli** [comment]
I'm not sure if this would be viable but would it be possible to not highlight $variables? This is a naming convention for global variables after all...

There definitely are more uses outside $variables where you might not use the exact symbol inside the Block but perhaps that would catch some of the values?

**Comment by szhorvat** [comment]
This is just opinion, but my preference would be to apply the principle of least surprise: do the  simple, predictable thing.

If it were possible for the plugin to fully understand Mathematica code and always make the correct decision, it would be good to do that. But this is not possible. So now there is a choice:

 - Apply simple rules that result in imperfect highlighting, but users can easily understand them
 - Apply complicated rules that still won't work for every situation, but they are hard to predict and confusion. Lots of people will complain because when the IDE trying to be smart to handle one case caused it to do something stupid for another one. The user experience suffers.

**Comment by halirutan** [comment]
@gerli Although I agree with Szabolcs, I also see your point. However, the "this is a naming convention" part is absolutely not true. I've seen people using all kinds of personal formatting conventions, many of which are not even consistent within a single notebook.

But your point of `Block` passing down the localized values to `f[]`, so that local variables do not necessarily appear in the body of `Block` is entirely true. There is no way for me to check this. Therefore, I added an option to the inspection that lets you turn off checking `Block` constructs.

![inspection](http://i.imgur.com/Z83UOpK.png)

This option will be available in the next [prerelease version](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases).
