### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by shrubbroom** [halirutan/Mathematica-IntelliJ-Plugin#142]
I am an undergraduate student in SJTU, Shanghai, China. And I use Wolfram language to make data analysis currently in a survey(my repo "TH020-Project") and do numerical computation in my math classes. I would like to apply for a free licence of this awesome plugin so that I can finish my work with Wolfram engine. Thanks a lot.

**Comment by halirutan** [comment]
@shrubbroom For the license-assignment, I need your email address because your license will be bound to this address. If you don't want to make it public here, please send me a short email with your _university address_. You get my email address by looking it up in my GitHub profile or by evaluating this in Mathematica

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by shrubbroom** [comment]
My email address is 
`Uncompress["1:eJxTTMoPChZjYGAozigqTUoqys/PdSjOKinVS00p1UvOAwCXvApi"]`
Regards.

**Comment by halirutan** [comment]
@shrubbroom Ahh, sorry, and I need your name as this is also part of the license. I forgot that.

**Comment by shrubbroom** [comment]
@halirutan Sorry for that ignorance, my name for JetBrain account is 'Ke Wu'.

**Comment by halirutan** [comment]
@shrubbroom Granted and you should receive a mail with your license.

**Comment by shrubbroom** [comment]
Yes, much gratitude
