### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by AlexeyPopkov** [halirutan/Mathematica-IntelliJ-Plugin#143]
I'm a scientist working in academia and I'm also an active member of the Mathematica.SE community:

https://mathematica.stackexchange.com/users/280/alexey-popkov

I'm planning to use the plugin in conjunction with the Free Wolfram Engine for Developers for participation in the community and development of some free extensions of the WL in situations when I have to work on a computer without the latest version of Wolfram Mathematica installed.

**Comment by halirutan** [comment]
Hey Alexey,

please send me an email to

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

with your academic email account and provide a link that verifies your affiliation with the institute (e.g. your staff page).

**Comment by AlexeyPopkov** [comment]
Hi Patrick,

I sent you an email. Did you get it?

**Comment by halirutan** [comment]
@AlexeyPopkov Yes, I did! It was a bit hectic in the last days. I already forwarded your request to Jetbrains the day you sent me the mail.

**Comment by halirutan** [comment]
@AlexeyPopkov Jetbrains told me that you don't have a Jetbrains account yet. Two things:

1. If you don't have a JB account, then you also don't use IDEA Ultimate or any other of the paid products. If you use IDEA Community, however, you can currently simply install the WL Plugin. This will change next year but for now the plugin is free on Community products.
2. If you do have a JB account, then it is not registered on your academic mail address. Please provide the mail address you have used with JB so that they can find your account and add the plugin license to it.

**Comment by AlexeyPopkov** [comment]
Thanks Patrick, 

I have created an account registered on my academic email address.

**Comment by halirutan** [comment]
@AlexeyPopkov Jetbrains still cannot find an account with your academic mail address. Can you log into [https://account.jetbrains.com/](https://account.jetbrains.com/), go to **Account** and make a screenshot. There should be your name and mail address visible and you could make a screenshot and send it to me.

**Comment by halirutan** [comment]
Granted
