### ISSUE TITLE
Incorrect symbol definition resolve

### ISSUE THREAD

**Issue by oovm** [halirutan/Mathematica-IntelliJ-Plugin#146]
```wl
c[w_] := 1 + (100000 / Pi) (Pi / w);
c[w_] := 1 + (100000 / Pi) * (Pi / w);
c[w_] := 1 + (Pi / w) (100000 / Pi);
c[w_] := 1 + (Pi / w) * (100000 / Pi);
```

![image](https://user-images.githubusercontent.com/17541209/71520189-c971d300-28f5-11ea-8c3e-41056aac20b3.png)

**Comment by halirutan** [comment]
That looks like an oversight in my parser for the "implicit multiplication" that happens between `() ()`. I'll look into it. Great short bug report! Thanks.

**Comment by halirutan** [comment]
@GalAster Just an update: I got a grip on this issue and I know its source. The problem is not your particular case (but kudos for providing such nice examples!). The main problem is that I need to get the parser working correctly so that it handles multiplication introduced by *some* whitespaces accurately.

**Comment by halirutan** [comment]
All tests pass, the parse-tree looks good and I cannot see any immediate issues. I'll include this fix in the next version.
