### ISSUE TITLE
Navigate to symbols from another file

### ISSUE THREAD

**Issue by mgroth0** [halirutan/Mathematica-IntelliJ-Plugin#148]
**Describe the bug**

I cannot navigate to the definition of a symbol in another file.

**To Reproduce**

Create two files:

### a.wl
```Mathematica
BeginPackage["a`"]
symbolOne = 1
<< b.wl
symbolOne = symbolTwo
Print[symbolOne]
EndPackage[]
```

### b.wl
```Mathematica
BeginPackage["b`"]
symbolTwo = 2
EndPackage[]
```

Running `wolframscript -f a.wl` correctly outputs `2`.

**Expected behaviour**

While editing a.wl, I'd like to be able to navigate to symbolTwo inside of b.wl. When I use the shortcut assigned to navigate while selecting `symbolOne`, I get a popup menu allowing me to navigate to its definition. However, `symbolTwo` inside of a.wl is not resolved by the ide and I cannot navigate to its definition.

**Please also provide:**
 - OS: Max OS X
 - IntelliJ Product: Ultimate 2019.3
 - Wolfram Plugin Version 2019.3

**Comment by halirutan** [comment]
Short answer:

- Ensure your files are within a [project module](https://wlplugin.halirutan.de/docs/projects-modules/) and marked as source
- Give the symbols you want to be visible throughout file boundaries a usage message by defining 

```wl
BeginPackage["b`"]
symbolTwo::usage = "My global variable that holds the value 2";
symbolTwo = 2
EndPackage[]
```

I take your example as what it is: A small example that you shouldn't do in real code, unless you know what you are doing.

The longer answer is: It is impossible to decide where a symbol is introduced until the Wolfram Kernel evaluates code. For instance this innocent-looking snippet

```wl
If[False,
 symbolTwo = 2;
 ]
```

introduces `symbolTwo` to the global name-space, although it never actually evaluates that part:

```wl
In[2]:= Names["Global`*"]

Out[2]= {"symbolTwo"}
```

For the Wolfram Language Plugin this means that we need a way to tell if a user wants to export a symbol from a file *without* evaluating the code. Because evaluation is something we cannot and don't want to do for many many reasons within the IDE.

The easiest and a quite performant solution is to check for usage-messages, because developers document the symbols they export from packages. In your toy example, it might look weird at first if you'd give a variable like `symbolTwo` a usage message, but in reality, many symbols that don't have any value get usage messages. Think about things like `Method` which is an option, doesn't have a value and is not a function. Still

```wl
In[4]:= MessageName[Method, "usage"]

Out[4]= "Method is an option for various algorithm-intensive functions that specifies what internal methods they should use."
```

**Comment by mgroth0** [comment]
I can confirm this works, and I am satisfied! Thank you.
