### ISSUE TITLE
Incorrect string recognition after Put

### ISSUE THREAD

**Issue by thompcinnamon** [halirutan/Mathematica-IntelliJ-Plugin#15]
The line `FullDefinition[output] >> "mathematicaHILLS.m"` gets the feedback "Could not parse right hand side of Put or PutAppend expression" as well as essentially missing the first quote symbol. It interprets it as opening a string at the end of the line that is then never closed.

The code runs just fine in Mathematica.
I do not know if this is an issue with the plugin or something from Mathematica, though I suspect more the latter, with no evidence.

![screen shot 2015-07-06 at 5 14 35 pm](https://cloud.githubusercontent.com/assets/8083606/8533365/8f113446-2402-11e5-993b-240f0e508b75.png)

**Comment by halirutan** [comment]
Definitely a bug in the plugin. I know when this was introduced and why it happens. Thanks for reporting back.

**Comment by halirutan** [comment]
Would you please use and test this [Mathematica-IntelliJ-Plugin-bin.zip](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/releases/tag/v0.3.6.2)? In IDEA go to Settings -> Plugins and use "Install from Disk". If there are no bad surprises with this fix, I'll push it to the main repository so that it is delivered to all other users. Thanks

**Comment by thompcinnamon** [comment]
![screen shot 2015-07-20 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/8083606/8785889/e4041e40-2ef8-11e5-94c7-cf55597e5740.png)

Seems to work now, and I don't see any other apparent issues. 

I also appreciate the added "missing semicolon" because that has killed my under-development packages many times!

**Comment by halirutan** [comment]
About the missing semicolon: At first I hesitated to include this, because it basically seems coding standard to **not** put semicolons after expressions in a package file. On the other hand, only advanced users understand that while

    expr1
    expr2

are two different expressions that are evaluated one after another at file scope, something like this

    {
      expr1
      expr2
    }

is parsed as `{expr1*expr2}`. I'm probably the only one who puts semicolons after each expression in a package file, but I think it is more consistent. If someone doesn't like the semicolon inspection, he can just turn it off.
