### ISSUE TITLE
Application for a free license

### ISSUE THREAD

**Issue by alexishughes** [halirutan/Mathematica-IntelliJ-Plugin#158]
To get a free license, I need some information. In the issue description, please provide information about how you want to use the plugin:

1. Links to open-source projects
anything you can find github.com/alexishughes is open source, but there's not much there worth a lot.
2. Information about academic or class-room usage
I am a student at Sussex University (MSc Computing) and my student email address (also jetbrains ID) is ah756@sussex.ac.uk

My Full name:
Alexis Hughes

Many thanks,

Wish I had more to say.

```
Uncompress["1:eJxTTMoPChZhYGAoSCwpykzOdshIzMksKi1JzNNLSQUAgX0JmQ=="]
```

**Comment by alexishughes** [comment]
FYI github.com/alexishughes/calc3 is quite good work but not complete

**Comment by halirutan** [comment]
Thanks for your interest! I requested a free license for you and report back soon.

**Comment by halirutan** [comment]
@alexishughes Your license has arrived :)

**Comment by alexishughes** [comment]
hi @halirutan, forgive my ignorance, instructions do not seem to work for CLION2020 or IDEA2020,
Particularly, "Browse Repositories" does not exist in the Apps. I was able to download Wolfram-IntelliJ-Plugin-2019.3.zip and tried to install from disk (using the zip file) but it waid it was incompatible.

Should I download previous version of IntelliJ or are there newer plugins or am I missing something simple.
:)

**Comment by halirutan** [comment]
Hey Alexis,

the version for 2020 is stable but since I want to finalize it and double-check support for Mathematica 12.1, it's still in the beta repository. Therefore, you just need to add Jetbrains beta repository to your list. It's only one step and I have described here how to do it

[Using EAP (beta) releases](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases)

I still struggle to find the right way to communicate with my users. We have a Plugin website, a LinkedIn group, a Gitter channel and most importantly a [Slack channel](https://join.slack.com/t/wolframlanguage/shared_invite/zt-67w2jpkn-vWd56pbKounvwkYC5z1SrQ) and I still have the feeling that many people are either afraid to ask or don't know where to read. That is not directed at you since you at least opened an issue here which is perfectly fine :)

So for instance, I announced how to use beta versions of the plugin in the documentation and in the LinkedIn group. Where would have been the right place that you would've found it?

**Comment by halirutan** [comment]
@alexishughes Sorry for not reading carefully enough. The IntelliJ Plugin settings basically work the same but got a slightly different UI. I have written "Browse repositories" on the WL Plugin webpage, but this is now simply "Marketplace" and you can search in the search bar on top. So

1. Subscribe to the beta repository as described in the documentation
2. Klick the Marketplace tab and search for "Wolfram"

This is how it looks in CLion 2020

![ing](http://i.imgur.com/Idp7qct.png)
