### ISSUE TITLE
IntelliJ 2020.1

### ISSUE THREAD

**Issue by adamhill** [halirutan/Mathematica-IntelliJ-Plugin#161]
**Describe the bug**
The plugin does not show up in the Plugins Marketplace. And if you download the latest release it will not install into IJ 2020.1

**To Reproduce**
1. Goto the Plugins Marketplace.
2. Try to search for "Wolfram"
3. Nothing shows up.
OR
1. Download latest ZIP from the releases Tab on Github. (mathematica-intellij-plugin-3.0beta1.zip)
2. Try to install from disk in the Gears menu in the Plugins Dialog
3. dialog says "Plugin 'Mathematica Support' is incompatible with this installation"

**Expected behaviour**
To install the plugin.

**Please also provide:**
 - OS: OSX 10.15.4
 - IntelliJ 2020.1.1
 - Wolfram Plugin Version plugin 3.0Beta (from the 2019.3 link on the main web page)

**Comment by halirutan** [comment]
@adamhill Do you already have a free or paid license? If not, please read [here first](https://wlplugin.halirutan.de/docs/licensing/).

To get the plugin version for IntelliJ 2020 products, please [read here](https://wlplugin.halirutan.de/docs/installation/#using-eap-beta-releases) and add the beta repository so that IntelliJ also searches there to find plugins.

**Comment by halirutan** [comment]
It's published now
