### ISSUE TITLE
menu item Wolfram Language .. FullForm  

### ISSUE THREAD

**Issue by allancto** [halirutan/Mathematica-IntelliJ-Plugin#193]
should produce Slot[1], not Slot[#][]

Input: 
Print[#]&["hi"] 

Incorrect: 
Function[Print[Slot[#][]]]["hi"] 

Correct: 
Function[Print[Slot[1]]["hi"]

**Comment by halirutan** [comment]
Better late than never. I fixed this for Slots, but remember that the plugin's _full form_ is not equivalent to the real `FullForm` of Mathematica. It's a full-form representation of the abstract syntax tree that the plugin builds internally of your code and I represent this tree as a fully-parenthesized code snippet. There are many more differences some of which can never be done correctly because Mathematica does things even before the expressions are parsed into a tree.

Fixed in development and will be published in the next release.

**Comment by allancto** [comment]
Thanks for the fix and thanks for the explanation. It's frustrating that Mathematica doesn't allow editing of expressions from trees, imo this is a serious problem that is unlikely to be addressed by the Mathematica team. 

Thanks @halirutan!
