### ISSUE TITLE
coloring non built-in symbols 

### ISSUE THREAD

**Issue by kubaPod** [halirutan/Mathematica-IntelliJ-Plugin#21]
Works, can be done with setting a color for "Identifier", but:
- Identifier is not the best name (maybe  Other symbols)
- In an example "Module" is colored too and that is completely confusing (it works ok in editor though)

**Comment by halirutan** [comment]
I'll call it `Symbols`. The reason is that the basic coloring for `Identifier` aka `Symbols` comes from the highlighter that is based on the lexer. Special colors like the green for `Module` variables or the color for built-in stuff is done at a later stage. There is not really a way to make them not pop up if you click on them in the color settings panel
