### ISSUE TITLE
Spellchecking for comments and strings 

### ISSUE THREAD

**Issue by kmisiunas** [halirutan/Mathematica-IntelliJ-Plugin#24]
Feature request: activate spell checking for comments and strings. Will help produce higher quality documentation. Also, thank you for making this plugin!

**Comment by halirutan** [comment]
It seems you didn't see our [Trello Roadmap Board](https://trello.com/b/qnblZBJi/mathematica-intellij-idea-plugin-roadmap) where you can vote for features?

I have put a link to the board on [my official Plugin Website](http://wlplugin.halirutan.de/). For *personal evaluation*, could you tell me whether you have checked the site or other resources? I want to know where I have to put news so that many users see them.

**Comment by kmisiunas** [comment]
Did not see that you had Trello for this. Thanks for pointing it out. 

I have seen the website, and it was useful the first time I started using the plugin. Thanks! But this time I did not check it, and went straight for github. I guess it is bit of a habit for me. Maybe it is worth adding the plugin on the GitHub's readme page as well. 

Thank you for developing it. I used to use sublime + Mathematica plugin, but now your plugin is much better. Thanks!

**Comment by halirutan** [comment]
The reason I ask is because we [discussed in chat](http://chat.stackexchange.com/rooms/8636/intellijidea-plugin-for-mathematica) what the best strategy is to reach users that are willing to give feedback. There are a million ways today: GitHub, Webpage, LinkedIn Group, Stackexchage, Twitter, Facebook etc and I'm not able to keep everything up to date. Therefore, your feedback is important. 

The 3 main places for information are:

- [www.mathematicaplugin.halirutan.de website](http://mathematicaplugin.halirutan.de/)
- [Stackexchange chat](http://chat.stackexchange.com/rooms/8636/intellijidea-plugin-for-mathematica)
- [GitHub README](https://github.com/halirutan/Mathematica-IntelliJ-Plugin) although I don't really put news and short-notices into the readme. That's why you missed the Trello board.

Anyway, I really appreciate your feedback and the work on the spell-check in strings and comments has already begun. I have currently a tight time table, so it might take a while.

Please, don't hesitate to write me if you have any other questions or suggestions.

**Comment by halirutan** [comment]
Fixed in development version
