### ISSUE TITLE
Built-in symbol highlighting broken in 1.3.3

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#28]
Built-in symbol highlighting got broken in 1.3.3.

![image](https://cloud.githubusercontent.com/assets/1212871/13770833/1aeac812-ea8a-11e5-9d83-72d457b9c2d4.png)

Module, If, While, True, etc. should be blue but they are white.

However, explicitly writing the context name highlights them again.

![image](https://cloud.githubusercontent.com/assets/1212871/13770902/731fe99a-ea8a-11e5-8729-62b57c2b3e88.png)

**Comment by halirutan** [comment]
Yes, I'm sorry. I reworked the whole thing how I store information about symbols and I now included context even for ``System` `` variables. This broke the highlighting since I didn't notice this commit went into the last release.

Fixed in 1.3.4

We definitely need to have a look at this whole mechanism since it doesn't take into account the the user could include packages etc.
