### ISSUE TITLE
definitions inside lists are not recognized/cataloged by the plugin. 

### ISSUE THREAD

**Issue by daliagachc** [halirutan/Mathematica-IntelliJ-Plugin#44]
I just noticed that if you define a variable/function inside a list, it is not recognized by the plugin. For example:
{
var = "var";
f[]:="function";
}
both var and f will not be cataloged by the plugin. 
Notice that although its not common practice to define variables like this, it is perfectly fine to do so in the notebook interface.

On a side note, I cant thank you enough halirutan for the plugin. It is so useful and gets updates all the time. 
Cheers

**Comment by halirutan** [comment]
Well, it is cataloged. If you open the StructureView (Alt+7), then you see indeed the definition for the symbols. What you probably mean is that it is not displayed in the autocompletion window when you type because these two things are unrelated. The StructureView is expensive to build up because finding definitions is not simple at all and I had to make an active decision on how to proceed exactly. The reason for this was that in Mathematica you can make global definitions wherever you like. Consider this unusual example which is perfectly valid code

```
Module[{x = (f[x_] := x^2; 3)},
  f[x]
]
```
After that we have a global function `f`. If the plugin is supposed to track all those things, it definitely needs to be able to evaluate the code like the Kernel does it. Only through evaluation it is possible to be sure to find all definitions and unfortunately this is not possible. Therefore, even the StructureView doesn't find all definitions and it can be tricked.

The autocompletion on the other hand needs to be very fast and therefore (if I remember correctly) it doesn't do such an extensive search like the StructureView does. This is why it doesn't suggest the functions. There is probably a way to make this working, but I haven't had time to look into this part of the IDEA API.

> Notice that although its not common practice to define variables like this, it is perfectly fine to do so in the notebook interface.

Yes, it's syntactically correct code, but it doesn't make sense. Why would you create a list `{Null}`? Because this is exactly what it is. More common is to use something like this if you don't need a `Module` or `Block`:

```
f[x_] := (Print[x]; x^2)
```

I'm leaving this issue open but don't get your hopes up that it will be fixed soon.

**Comment by halirutan** [comment]
Fixed in the development version. See my last comment here

https://github.com/halirutan/Mathematica-IntelliJ-Plugin/issues/46
