### ISSUE TITLE
Autocompletion for symbols mentioned at top level

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#46]
Personally I would find it useful to enable autocompletion for all symbols mentioned at the top level.  Example:

```
foo[x_] := (y=x^2; y)

bar

baz;
```

There will be no auto-completion at the top level for `x`, `y`, `bar` and `baz`.  There will be for `foo`.

I would find it useful to also have it for `bar` and `baz`.

There are situations when some global symbols I use do not get defined at the top level for some reason.  I want auto-completion for these.  Example of how this can happen:

Conditional definition:

```
If[$OperatingSystem === "Windows",
  fun[] := ...
  ,
  fun[] := ...
]
```

Certain special initialization:

```
loadStuff[] := (various initializations; myGlobalVar=1;)

ReloadPackage[]:= (...; loadStuff[]; ...)
```

My typical use case for a function like `ReloadPackage[]` is to recompile LibraryLink stuff, and then re-do the necessary initialization.

**Comment by halirutan** [comment]
The behavior is on purpose, but not to annoy you. It is to keep the highlighting and autocompletion performance high. It is kind of related to an [issue that I fixed](http://chat.stackexchange.com/transcript/message/16395949#16395949) a while ago.

Therefore, there are certain restrictions when a symbol is considered to have values defined. One restriction is that it really needs to be given a value somehow. Be it with `DownValues` or by giving it a message. The second is, that global definitions can currently only appear at file-level. I might consider lifting this restriction a bit because the `If[ValueQ[..],..]` template is often used when defining symbols. What I will not do is to dive into `Module` or other localization things and search for definitions. Maybe I'm considering a white-list of functions like `If` or even parentheses. 

Nevertheless, you should get *all symbols* inside your file completed using explicit `Ctrl+Space` (or `Ctrl+Alt+Space`, but Jetbrains seems to have simplified this). For such an explicit call, the algorithm will really suggest all identifiers it finds in the code.

**Comment by halirutan** [comment]
Fixed in the development version. It seems I'm on the right track. The reference resolving works quite well and finds now definitions wherever they may be. Resolved global definitions are cached and instantly available for completion.

The bottleneck is still the resolver for file-global functions on very large files (And I don't need to look at someone, do I?), but I will see how we can handle this.
