### ISSUE TITLE
No way to set highlight color for local variables

### ISSUE THREAD

**Issue by Axure** [halirutan/Mathematica-IntelliJ-Plugin#47]
The setting for the color of local variables (bordered in the picture) seems missing. It seem to inherit from some other settings (or not), and there is no way to change it.

![mathematica intellij](https://cloud.githubusercontent.com/assets/3424317/16399904/2428a7b0-3d09-11e6-88b4-c02e58fe910a.png)

**Comment by halirutan** [comment]
Yes, it is correct the it is currently not possible to set all available colors from within the color-setting panel. There is a hack around it if you want to change it right now:

- download the [color xml file](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/tree/develop/resources/colors) for the scheme you are using
- download the [latest plugin zip](https://plugins.jetbrains.com/plugin/7232?pr=idea)
- edit the colors xml file as you like
- inside the zip file, open the Mathematica-IntelliJ-Plugin.jar and inside this, navigate to the `colors` directory and replace the existing xml with your changed version
- install the plugin zip from within IDEA by using "install from disk"

## The correct way to fix this issue once and for all times

There is more to this issue. It you watch closely, you will find that for instance `Block` uses a slightly other color for localized variables. This is not even reflected in the color-setting panel. The reason is simple, the demo-code that is shown there is not highlighted by IDEA but needs to be marked manually. It can be found [here](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/develop/resources/colors/demoText.txt) and looks like this

```
VariationalD[<pat>f_</pat>, (<pat>y_</pat>)[<pat>x_</pat>, <pat>r___</pat>], <pat>w</pat>:{<pat>x_</pat>, <pat>r___</pat>}]/;integrandQ[<pat>f</pat>] :=
  Module[{<mod>Dfuncs</mod>, <mod>Dtimes</mod>, <mod>dummyfunc</mod>},
    <mod>Dfuncs</mod> = <k>Union</k>[<k>Cases</k>[{<pat>f</pat>}, <k>Derivative</k>[__][<pat>y</pat>][__], <k>Infinity</k>]];
    <mod>Dtimes</mod> = (<k>Head</k>[<k>Head</k>[<slot>#1</slot>]] & ) /@ <mod>Dfuncs</mod> /. <k>Derivative</k> -> <k>List</k>;
    <k>Simplify</k>[<k>D</k>[<pat>f</pat>, <pat>y</pat>[<pat>x</pat>, <pat>r</pat>]] + (<k>ReleaseHold</k>[<k>Thread</k>[<mod>dummyfunc</mod>[(<k>D</k>[<pat>f</pat>,
        <slot>#1</slot>] & ) /@ <mod>Dfuncs</mod>,
             (<k>Hold</k>[<k>Apply</k>[<k>Sequence</k>, <slot>#</slot>]] & ) /@
              (<k>Thread</k>[{<pat>w</pat>, <slot>#1</slot>}] & ) /@ <mod>Dtimes</mod>]]] /. <mod>dummyfunc</mod> -> <k>D</k>) .
        <fn>((-1)^<slot>#1</slot> & ) /@ (<k>Apply</k>[<k>Plus</k>, <slot>#1</slot>] &</fn> ) /@ <mod>Dtimes</mod>] ]
```

So every part that is not highlighted by the *basic lexer* needs to be tagged. As you can see, operator signs and simple identifiers are things the lexer already knows. Localization variables or what a `Message` is, is done in a later stage. So for instance the keywords `<k>` are usual identifiers, but the information that they are built-in functions is added later in the highlighting process.

To make this color-panel complete, we first need a demo code that reflects all possible things the highlighter can do. Then, someone needs to add the html-tags to the demo-text and finally, I need to do some small changes in the code to add the possibility to edit the colors.

If you feel like you are up to this challenge just drop me a line.

**Comment by kubaPod** [comment]
@halirutan  is it possible to edit that file to reflect SyntaxInformation of custom scoping constructs?

**Comment by halirutan** [comment]
@kubaPod This file is really only for choosing the color. The highlighting itself, and especially the logic that traces local variables, is done in code and not easily accessible.

**Comment by kubaPod** [comment]
@halirutan  even if the custom function have the same structure as With? Is there any shortcut? I don't need to do this for many symbols but I use one as a part of a "framework" I'm working on and it would be very nice to have its variables highlighted, even more if that can be done in different color than Module or patterns.

**Comment by halirutan** [comment]
This is fixed int the development version and will be published soon.
