### ISSUE TITLE
Enhancement: `{x = 5}~With~x` support

### ISSUE THREAD

**Issue by Masterxilo** [halirutan/Mathematica-IntelliJ-Plugin#53]
I sometimes write `With` statements like this, but the plugin unfortunately does not recognize them (meaning the `x` is not properly highlighted on the rhs).
A more uniform handling of binary operators should allow doing this.

Interestingly, not even the MM 11 notebook interface supports this.

**Comment by halirutan** [comment]
The problem you face here is larger than you might think. The highlighting (in *Mathematica* or in IntelliJ) is based on the source-code in its unevaluated form: the abstract syntax tree (AST). Everything else could not be guaranteed to work quick enough. Therefore, to start with a simple example please look at the following snipped of code

```mma
f = With;
f[{x = 5}, x]
```
It's clear that `f` is `With` but still the highlighting will not work because the AST looks like this

![Mathematica graphics](http://i.stack.imgur.com/1sw7Y.png)

and the hightlighter cannot know that `f` on the right side is indeed `With` without evaluating the code. 

The usual response to such a simple example is to say "OK, why isn't it possible to search where `f` is defined"? Well, the problem is, that the evaluation of `f` may lead to the evaluation of very complicated expressions. Therefore, the syntax-highlighter usually does not evaluate anything at all. You can see it in extreme simple examples that break the highlighting in *Mathematica*

![Mathematica graphics](http://i.stack.imgur.com/0oeND.png)

or 

![Mathematica graphics](http://i.stack.imgur.com/HeF4I.png)

Therefore, your infix notation of `With` is only one of many examples that are not supported. I personally have never seen someone who writes `{x = 5}~With~x` and premise for the highlighter is to work as fast as possible to make writing code smooth and painless. This cannot be guaranteed when it supports all possible ways of writing code, especially in a language like WL.

**Comment by Masterxilo** [comment]
I completely understand the argumentation that the parser should not need to be turing complete. But "a~f~b" is a syntactic-variant, not a runtime-variant on "f[a,b]".

The notebook's parser knows this, correctly highlighting the right parts when stepping through the expression tree with Ctrl+.

**Comment by halirutan** [comment]
> Interestingly, the notebook's parser does not know that "1~f~2~f~3" becomes "f[f[1,2],3]". It stores "RowBox[{"1", "~", "f", "~", "2", "~", "f", "~", "3"}]"

Well, the situation in the frontend is entangled enough and you cannot strictly speak about *the* notebook's parser. There is something working that turns code you are typing into the box-form and as your example clearly shows, this box-form is not equivalent to a syntax or parse tree.

I remember a chat with John Fultz, the lead FE developer and he said "I wrote several parsers for different tasks". Therefore, I'm would not be surprised if there are several different algorithms running in the background of the FE.

Clear is the following:

1. The IntelliJ Plugin has exactly one lexer and one parser that translates input code into a syntax tree that is filled with semantic information (like which variable is localized by which `Module` or `Table`). All the nifty highlighting in the Plugin use this syntax tree and therefore, your example `1~f~2~f~3` is indeed parsed correctly. Therefore, you can use `Ctrl+W` to select step-wise `1~f~2`
2. In *Mathematica* the real parser that is used to evaluate code is called when you press `Shift+Enter`. Everything else is done inside the FE.
