### ISSUE TITLE
Refactoring: change text in usage messages

### ISSUE THREAD

**Issue by szhorvat** [halirutan/Mathematica-IntelliJ-Plugin#58]
This is a feature suggestion.

When renaming symbol `f` to `g` using the refactoring tools,

    f::usage = "f..."

should change to 

    g::usage = "g..."

provided that the usage string starts *exactly* with `f`.

**Comment by halirutan** [comment]
Renaming works by reference resolving. Therefore if you have 

```mathematica
myFunction::usage = "myFunction[x] works like this";

SetAttributes[myFunction, {Listable}];

myFunction[x_] := x^2;
```

the renaming of `myFunction` works because the point of declaration and all its usages are found an algorithm. The standard renaming works by renaming all found instances of `myFunction`. My hope is that I can *extend* the default `RenameHandler` by visiting all elements that are going to be renamed and check if one of the constructs is a usage message. With this, I can make this feature very safe.

I asked on the IntelliJ Community [in thispost](https://intellij-support.jetbrains.com/hc/en-us/community/posts/205436630-Extend-RenameHandler-to-handle-specific-strings).

**Comment by szhorvat** [comment]
This is now implemented.
