### ISSUE TITLE
Multiple click to extend selection

### ISSUE THREAD

**Issue by drewsteinacher** [halirutan/Mathematica-IntelliJ-Plugin#64]
Thanks for the great work on this plugin! I really like it!
However, it's missing one feature that's very important to me: Multiple click to extend selection.

I am aware that the editor already supports Ctrl + W to do this, but it's much easier (and more like the Mathematica Front End and Wolfram Workbench) if it were handled via multiple click.

I was able to work around it a little bit by adding a mouse shortcut to "Extend selection" for double-click, but it isn't quite the same.

Consider the following code:

```Mathematica
foo[n_Integer] := With[{},
	Partition[Range[1, n], 2, 1]
]
```

Double-clicking on the head of an expression (e.g. Range) will highlight the entire expression, but in Mathematica it only highlights the head.
Similarly, multiple-clicking on the head of an expression will highlight the whole line and stop there. In Mathematica, it will continue to extend the selection (e.g. triple clicking Range will highlight the whole Range expression).

This is very useful when copying/pasting code, determining precedence, and even seeing how the code will parsed/evaluated.

Would it be possible to add this feature?
So far, it looks like 3+ clicks will only select the entire line, and there is no way to add a triple-click mouse shortcut.

I'd really like it, as the formatting in this IDE and this plugin (Ctrl + Alt + L) is very, very much preferable to the one built into the Wolfram Workbench plugin.

Again, thanks for the great work!

**Comment by halirutan** [comment]
Unfortunately, I have no good news for you. For one, the plugin doesn't alter such core editor facilities, and extension points for this do not exist to my knowledge. IDEA is very keyboard-centric because most programmers prefer to stay with their hands on the keys the whole time. Additionally, double click and triple click is already bound to the actions "select identifier under cursor" and "select whole line". I quickly checked all possible extension points, and there just isn't anything that looks like I could override the default mouse action.

> I'd really like it, as the formatting in this IDE and this plugin (Ctrl + Alt + L) is very, very much preferable to the one built into the Wolfram Workbench plugin.

Note that it is still the very first version I hacked for the formatting engine. I thought about re-implementing it several times, but the truth is that it is just hard to make the formatting more strict without annoying some users. For instance, sometimes you probably want a `Module` to fit into a single line like

```Mathematica
Module[{var1,var2},body]
```

while most of the times, modules should be laid out like this

```Mathematica
Module[
  {
    var1,
    var2
  },
  body
]
```

There are cases, where users want to keep the variable definitions in one line, etc.. Therefore, the formatter tries to keep everything as the user typed it and just takes care of correct indentation and spaces between operator.
