### ISSUE TITLE
Extended characters, which are inputted as \:<SomeHexNumber>, are not processed properly.

### ISSUE THREAD

**Issue by kkkmail** [halirutan/Mathematica-IntelliJ-Plugin#65]
If Mathematica m file contains extended characters, which are inputted as `\:<SomeHexNumber>` then the following occurs:
1. IntelliJ generates an error "Closing ']' expected" on the first occurrence and then "The last expression could not be parsed correctly" on all subsequent occurrences. 
2. Attempt to reformat the code CTRL+A, then CTRL+ALT+L results in ":" acquiring a space before and after it.

For example, if the following code is reformatted

`\[Gamma]\:02d6 = 0;
`

then it becomes:

`\[Gamma]\ : 02d6 = 0;
`

Subsequently, Mathematica can no longer correctly parse the file.

**Comment by halirutan** [comment]
Yes, this is a limitation, but including it in the plugin needs a change in the lexer, the parser and the whole syntax machinery and would only add a feature most users will never use. Please note that you can still many Unicode characters by directly typing them (on my Linux box I need to press `Ctrl`+`Shift`+`u` and then the code number to get e.g. `α`).

Additionally, the plugin is made for package writers that write plain ASCII `.m` files. If you look through all of the *AddOn* packages, you won't find this form of Unicode variables in human readable code and there is a good reason for it: You and others want to read the code over and over again.
I don't think anyone ever wants to see something like

```
"CLEAR-NAME"->"\:042f\:0441\:043d\:043e\:0441\:0442\:044c"
```
in code. I understand that this limits some users, but I'm sure even Korean developers type Unicode directly instead of inserting this form into a file.
