### ISSUE TITLE
Reformatting According to Specified Code Style Not Working

### ISSUE THREAD

**Issue by hbuchman** [halirutan/Mathematica-IntelliJ-Plugin#82]
After I updated IntelliJ to IntelliJ IDEA 2017.2.1 (community edition), the 'Spaces' section in Editor -> Code Style -> Mathematica stopped respecting my space removals. When I try and Reformat with Ctrl+Atl+L, regardless of how I have the spaces configured, it adds spaces everywhere. The example code shown on the right of the check boxes also does not dynamically update like it used to.

I am on a Windows 7 machine. My Mathematica Support plugin is on version 2.4.4. Previously I was running a version of IntelliJ that was ~1.5 years old.  My space settings are respected for other languages.

![image](https://user-images.githubusercontent.com/10619752/28906080-e397d156-77c9-11e7-95b9-33245e458d2e.png)

Thanks! I really appreciate having this plugin available.

**Comment by simonkeys** [comment]
I have also run into this. IntelliJ IDEA 2017.2.1, Mathematica Support 2.4.4, OS X 10.10.5.

**Comment by halirutan** [comment]
That code is now 5 years old :)

Would you try [this plugin version](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/releases/tag/v2.4.5) by manually downloading and installing it?

**Comment by hbuchman** [comment]
Thanks so much. That worked for me! I'm not sure what the typical flow is, but from my perspective this issue is now closed.

**Comment by halirutan** [comment]
The problem simply was that the settings were not saved correctly anymore in version 2017.2. So even if you deselected something, the next time you open the settings, the default (everything is selected) was re-applied. It was a simple fix. Only debugging what was going on took a while.
It turned out that I was not handling settings correctly from the very beginning, but it happened to work until the new version.

I'm currently working on re-implementing some core functionalities and it will take some time until I have a version that finally works at least as good as the last one (although the future benefits will be large). You can just use the manually installed version you have now and the moment I'm putting out a new release it will contain this fix and you will be notified for an update.

Thanks for this very detailed report and for paying attention.
